### ISSUE TITLE
Language Model and necessary files?

### ISSUE THREAD

**Issue by mingzi151** [jzhou316/Unsupervised-Sentence-Summarization#2]
Hi, can you release the Language Model and necessary files to run the code? 

On another node,  the file pre_word_list.py contains the following line of code:

subvocab_embed_mask[subvocab_embed[subvocab_embed >= numwords_freq]] = 1  # never remove the most frequent words

I wondered if ">=" should be "<". A typo?

**Comment by mingzi151** [comment]
Hi, thanks for releasing the code. I wondered if you are able to provide pre-trained lm and the vocab file. By vocab file, I'm referring to the one with the name "vocabsctgt.pkl", shown in summary_search_elmo.py file. Many thanks.

**Comment by jzhou316** [comment]
Hi sorry for the late response. 

For the line in file pre_word_list.py:
`
subvocab_embed_mask[subvocab_embed[subvocab_embed >= numwords_freq]] = 1 # never remove the most frequent words
`
It is not a typo, because I was using the xor operation ^ [the line below](https://github.com/jzhou316/Unsupervised-Sentence-Summarization/blob/5e42514d5f6e8250a2f0b375bc28bad4a7e67739/uss/pre_word_list.py#L102) 
`
subvocab_screened_mask = (subvocab_mask ^ subvocab_embed_mask) & subvocab_mask
`
to compute the correct mask, so that the positions marked by 1 in `subvocab_embed_mask` will not be selected.

And I have released the pre-trained [language models](https://github.com/jzhou316/Unsupervised-Sentence-Summarization#datasets--summary-results--pre-trained-language-models), along with the vocabulary files associated with them. You should be able to directly run the code with these resources now without any training needed. Thanks.
